const countriesData = [
  {
    abbrev: 'US',
    name: 'United States',
    postalCodePattern: '99999 or 99999-9999',
    postalRegex: '^\\d{5}(?:[-\\s]\\d{4})?$',
  },
  {
    abbrev: 'CA',
    name: 'Canada',
    postalCodePattern: 'A9A 9A9 or A9A-9A9',
    postalRegex: '^[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] ?[0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]$',
  },
  {
    abbrev: 'GB',
    name: 'United Kingdom',
    postalCodePattern: 'AAA 9AA or AA99 9AA or AA9 9AA',
    postalRegex:
      '^(GIR\\s?0AA|[A-PR-UWYZ]\\d{1,2}[A-HK-Y]?\\d{1,2}[ABEHMNPRVWXY]?\\s?\\d{1,2}[ABD-HJLN-UW-Z]{2}|ASCN\\s?1ZZ|STHL\\s?1ZZ|TDCU\\s?1ZZ|BBND\\s?1ZZ|BIQQ\\s?1ZZ|FIQQ\\s?1ZZ|PCRN\\s?1ZZ|SIQQ\\s?1ZZ|TKCA\\s?1ZZ)$',
  },
  {
    abbrev: 'AR',
    name: 'Argentina',
    postalCodePattern: 'A9999AAA',
    postalRegex: '^[A-HJ-NP-Z]{1}[0-9]{4}[A-Z]{3}$',
  },
  {
    abbrev: 'AU',
    name: 'Australia',
    postalCodePattern: '9999',
    postalRegex: '^[0-9]{4}$',
  },
  {
    abbrev: 'AT',
    name: 'Austria',
    postalCodePattern: '9999',
    postalRegex: '^[0-9]{4}$',
  },
  {
    abbrev: 'BE',
    name: 'Belgium',
    postalCodePattern: '9999',
    postalRegex: '^[0-9]{4}$',
  },
  {
    abbrev: 'BR',
    name: 'Brazil',
    postalCodePattern: '99999 or 99999-999',
    postalRegex: '^\\d{5}(?:[-]\\d{3})?$',
  },
  {
    abbrev: 'BG',
    name: 'Bulgaria',
    postalCodePattern: '9999',
    postalRegex: '^[0-9]{4}$',
  },
  {
    abbrev: 'KH',
    name: 'Cambodia',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'CL',
    name: 'Chile',
    postalCodePattern: '9999999 or 999-9999',
    postalRegex: '^(\\d{7}|\\d{3}-\\d{4})$',
  },
  {
    abbrev: 'CO',
    name: 'Colombia',
    postalCodePattern: '999999',
    postalRegex: '^[0-9]{6}$',
  },
  {
    abbrev: 'HR',
    name: 'Croatia',
    postalCodePattern: '99999',
    postalRegex: '^[0-9]{5}$',
  },
  {
    abbrev: 'CR',
    name: 'Costa Rica',
    postalCodePattern: '99999 or 99999-9999',
    postalRegex: '^\\d{5}(?:[-]\\d{4})?$',
  },
  {
    abbrev: 'DK',
    name: 'Denmark',
    postalCodePattern: '9999 or 99',
    postalRegex: '^(?:DK-)?\\d{4}$',
  },
  {
    abbrev: 'DO',
    name: 'Dominican Republic',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'EC',
    name: 'Ecuador',
    postalCodePattern: '999999',
    postalRegex: '^[0-9]{6}$',
  },
  {
    abbrev: 'EG',
    name: 'Egypt',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'EE',
    name: 'Estonia',
    postalCodePattern: '99999',
    postalRegex: '^[0-9]{5}$',
  },
  {
    abbrev: 'FI',
    name: 'Finland',
    postalCodePattern: '99999',
    postalRegex: '^(?:FI-)?\\d{5}$',
  },
  {
    abbrev: 'FR',
    name: 'France',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'DE',
    name: 'Germany',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'GR',
    name: 'Greece',
    postalCodePattern: '99 99',
    postalRegex: '^\\d{2} \\d{2}$',
  },
  {
    abbrev: 'GT',
    name: 'Guatemala',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'HU',
    name: 'Hungary',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'IN',
    name: 'India',
    postalCodePattern: '999 999 or 999999',
    postalRegex: '^\\d{6}$',
  },
  {
    abbrev: 'ID',
    name: 'Indonesia',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'IE',
    name: 'Ireland',
    postalCodePattern: 'A99 A9A9 or A99 AA99 or A99 A9AA',
    postalRegex: '^[A-Za-z]{3}\\d{2}[A-Za-z]{4}$',
  },
  {
    abbrev: 'IT',
    name: 'Italy',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'JO',
    name: 'Jordan',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'KW',
    name: 'Kuwait',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'LV',
    name: 'Latvia',
    postalCodePattern: '9999',
    postalRegex: '^[0-9]{4}$',
  },
  {
    abbrev: 'LT',
    name: 'Lithuania',
    postalCodePattern: '99999',
    postalRegex: '^[0-9]{5}$',
  },
  {
    abbrev: 'LU',
    name: 'Luxembourg',
    postalCodePattern: '99999',
    postalRegex: '^[0-9]{5}$',
  },
  {
    abbrev: 'MY',
    name: 'Malaysia',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'MT',
    name: 'Malta',
    postalCodePattern: 'AAA 9999',
    postalRegex: '^[A-Za-z]{3}\\s\\d{4}$',
  },
  {
    abbrev: 'MX',
    name: 'Mexico',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'ME',
    name: 'Montenegro',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'NZ',
    name: 'New Zealand',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'NO',
    name: 'Norway',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'OM',
    name: 'Oman',
    postalCodePattern: '999',
    postalRegex: '^\\d{3}$',
  },
  {
    abbrev: 'PK',
    name: 'Pakistan',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'PY',
    name: 'Paraguay',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'PE',
    name: 'Peru',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'PH',
    name: 'Philippines',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'PL',
    name: 'Poland',
    postalCodePattern: '99-999',
    postalRegex: '^\\d{2}-\\d{3}$',
  },
  {
    abbrev: 'PT',
    name: 'Portugal',
    postalCodePattern: '9999-999',
    postalRegex: '^\\d{4}-\\d{3}$',
  },
  {
    abbrev: 'RO',
    name: 'Romania',
    postalCodePattern: '999999',
    postalRegex: '^\\d{6}$',
  },
  {
    abbrev: 'RU',
    name: 'Russia',
    postalCodePattern: '999999',
    postalRegex: '^\\d{6}$',
  },
  {
    abbrev: 'SA',
    name: 'Saudi Arabia',
    postalCodePattern: '99999-9999',
    postalRegex: '^\\d{5}-\\d{4}$',
  },
  {
    abbrev: 'RS',
    name: 'Serbia',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'SG',
    name: 'Singapore',
    postalCodePattern: '999999',
    postalRegex: '^\\d{6}$',
  },
  {
    abbrev: 'SK',
    name: 'Slovak Republic',
    postalCodePattern: '99999 or 999 99',
    postalRegex: '^\\d{5}|\\d{3}\\s\\d{2}$',
  },
  {
    abbrev: 'SI',
    name: 'Slovenia',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'ZA',
    name: 'South Africa',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'ES',
    name: 'Spain',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'SE',
    name: 'Sweden',
    postalCodePattern: 'SE-999-99 or 999-99 or 999 99 or 99999',
    postalRegex: '^(SE-\\d{3}-\\d{2}|\\d{3}-\\d{2}|\\d{3}\\s\\d{2}|\\d{5})$',
  },
  {
    abbrev: 'CH',
    name: 'Switzerland',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'TW',
    name: 'Taiwan',
    postalCodePattern: '999 or 999999 or 999-999',
    postalRegex: '^\\d{3}|\\d{6}|\\d{3}-\\d{3}$',
  },
  {
    abbrev: 'TH',
    name: 'Thailand',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'TN',
    name: 'Tunisia',
    postalCodePattern: '9999',
    postalRegex: '^\\d{4}$',
  },
  {
    abbrev: 'TR',
    name: 'Turkey',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'UA',
    name: 'Ukraine',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'UY',
    name: 'Uruguay',
    postalCodePattern: '99999',
    postalRegex: '^\\d{5}$',
  },
  {
    abbrev: 'VE',
    name: 'Venezuela',
    postalCodePattern: '9999 or 9999-A',
    postalRegex: '^\\d{4}|\\d{4}-[A-Z]$',
  },
  {
    abbrev: 'VN',
    name: 'Vietnam',
    postalCodePattern: '999999',
    postalRegex: '^\\d{6}$',
  },
];

module.exports = countriesData;
