  /products:
    get:
      summary: Get product.
      tags: [Products]
      description: Get product by vendor code.
      parameters:
        - in: query
          name: vc
          schema:
            type: number
          required: true
          description: The vendor code of the product.
          example: 671296
      responses:
        200:
          description: Successful retrieval of the product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    post:
      summary: Fetch products
      tags: [Products]
      description: Get products by filters
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: category of products (bikes or accessories)
                  example: bikes
                minPrice:
                  type: number
                  description: Minimum price value of range ($)
                  example: 100
                maxPrice:
                  type: number
                  description: Maximum price value of range ($)
                  example: 2000
                weight:
                  type: number
                  description: Maximum rider weight (100 - 130 kg (step 15))
                  example: 115
                minBase:
                  type: number
                  description: Minimum bike wheel base of range (mm)
                  example: 1000
                maxBase:
                  type: number
                  description: Maximum bike wheel base of range (mm)
                  example: 1100
                frameSize:
                  type: number
                  description: Frame bike size (mm)
                  example: 450
      responses:
        200:
          description: Successful retrieval of the list of the products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        400:
          description: Bad Request.
        5XX:
          description: Unexpected error